(()=>{
 const defaults={showPlaceholder:true,protectionEnabled:true,etsyEnabled:true,blockedEtsyShops:[],manualFlags:[],hiddenItems:[],customTerms:""};let settings={...defaults};const S=FeedShieldItemSafety;
 const norm=s=>(typeof s==='string'?s:"").toLowerCase().replace(/\s+/g," ").trim(),custom=()=>String(settings.customTerms||"").split(/\n|,/).map(norm).filter(Boolean);
 function listingCards(){const set=new Set();document.querySelectorAll('a[href*="/listing/"]').forEach(a=>{const c=a.closest('li,article,[data-listing-id],div.wt-grid__item-xs-6');if(c&&S.pageText(c).trim().length>3)set.add(c)});return[...set]}
 function shopName(card){for(const s of ['[data-shop-name]','.v2-listing-card__shop','.wt-text-caption','a[href*="/shop/"]']){const e=card.querySelector(s),v=e?.getAttribute('data-shop-name')||e?.textContent?.trim();if(v&&v.length<100)return v}return"Unknown shop"}
 function saveFlag(meta){if(FeedShieldBrowser.activity)return FeedShieldBrowser.activity({report:meta,operations:meta.url?[{key:"hiddenItems",value:meta.url}]:[]});return new Promise(r=>FeedShieldBrowser.legacy.storage.local.get({manualFlags:[],hiddenItems:[]},o=>{const a=Array.isArray(o.manualFlags)?o.manualFlags:[],h=Array.isArray(o.hiddenItems)?o.hiddenItems:[];a.unshift(meta);if(meta.url&&!h.includes(meta.url))h.unshift(meta.url);FeedShieldBrowser.legacy.storage.local.set({manualFlags:a,hiddenItems:h},r)}))}
 function blockShop(name){if(FeedShieldBrowser.activity&&name&&name!=="Unknown shop")return FeedShieldBrowser.activity({operations:[{key:"blockedEtsyShops",value:name}]});return new Promise(r=>{if(!name||name==="Unknown shop"){r();return}FeedShieldBrowser.legacy.storage.local.get({blockedEtsyShops:[]},o=>{const a=o.blockedEtsyShops||[];if(!a.map(norm).includes(norm(name)))a.push(name);FeedShieldBrowser.legacy.storage.local.set({blockedEtsyShops:a},r)})})}
 function undoBar(card,msg,url,shop){
  if(!S.current(card,'Etsy',url)||!settings.protectionEnabled||!settings.etsyEnabled)return;S.hide(card,url,{replace:settings.showPlaceholder,reason:'You chose to hide this item'});const old=document.querySelector(".feedshield-undo");if(old)old.remove();const bar=document.createElement("div");bar.className="feedshield-undo";bar.dataset.feedshieldOwnerRef=card.dataset.feedshieldOwner;bar.textContent=msg+" ";const b=document.createElement("button");b.textContent="Undo";b.onclick=()=>FeedShieldBrowser.activity?FeedShieldBrowser.activity({operations:[{key:"hiddenItems",value:url,remove:true},...(shop?[{key:"blockedEtsyShops",value:shop,remove:true}]:[])]}).then(update=>{Object.assign(settings,update);if(S.current(card,"Etsy",url)){S.restore(card);add(card);}bar.remove();}).catch(FeedShieldBrowser.report):FeedShieldBrowser.legacy.storage.local.get({hiddenItems:[],blockedEtsyShops:[]},o=>{const update={hiddenItems:(o.hiddenItems||[]).filter(x=>x!==url)};if(shop)update.blockedEtsyShops=(o.blockedEtsyShops||[]).filter(x=>norm(x)!==norm(shop));FeedShieldBrowser.legacy.storage.local.set(update,()=>{Object.assign(settings,update);if(S.current(card,'Etsy',url))S.restore(card);bar.remove();add(card)})});bar.append(b);document.documentElement.append(bar);setTimeout(()=>bar.remove(),7000)
 }
 function add(card){
  const url=S.bind(card,'Etsy');if(!url)return;const shop=shopName(card),text=norm(S.pageText(card));
  if(card.dataset.feedshieldReveal!==url&&(S.savedMatch(settings.hiddenItems,url,'Etsy')||(settings.blockedEtsyShops||[]).map(norm).includes(norm(shop))||custom().some(x=>text.includes(x)))){S.hide(card,url,{replace:settings.showPlaceholder,reason:S.savedMatch(settings.hiddenItems,url,'Etsy')?'You chose to hide this item':(settings.blockedEtsyShops||[]).map(norm).includes(norm(shop))?'Blocked shop':'Matched a muted word'});return}
  if(card.dataset.feedshieldHiddenBy==='FeedShield')S.restore(card);if(card.dataset.feedshieldEtsy==='1')return;
  card.dataset.feedshieldEtsy="1";const wrap=document.createElement("div");wrap.className="feedshield-etsy-controls";const trigger=document.createElement("button");trigger.textContent="Tell FeedShield";
  trigger.onclick=e=>{e.preventDefault();e.stopPropagation();if(!S.current(card,'Etsy',url))return;const old=wrap.querySelector(".feedshield-etsy-menu");if(old){old.remove();return}const menu=document.createElement("div");menu.className="feedshield-etsy-menu";
   ["Suspected AI-generated artwork","AI-generated product mockup","Misleading handmade claim","Copied or mass-produced artwork","Product image may not match item","Suspicious digital download","Disturbing or sexualized image","Hide this shop","Something else"].forEach(reason=>{const b=document.createElement("button");b.textContent=reason;if(reason==="Hide this shop")b.className="danger";b.onclick=async ev=>{ev.preventDefault();ev.stopPropagation();if(!S.current(card,'Etsy',url))return;const meta={site:"Etsy",reason,shop,url,title:S.pageText(card).slice(0,240),flaggedAt:new Date().toISOString()};await saveFlag(meta);if(!S.current(card,'Etsy',url)||!settings.protectionEnabled||!settings.etsyEnabled)return;if(reason==="Hide this shop"){await blockShop(shop);if(!S.current(card,'Etsy',url)||!settings.protectionEnabled||!settings.etsyEnabled)return;document.querySelectorAll('[data-feedshield-item-site="Etsy"]').forEach(x=>{const key=S.bind(x,'Etsy');if(key&&norm(shopName(x))===norm(shop))S.hide(x,key,{replace:settings.showPlaceholder,reason:'Blocked shop'})});undoBar(card,"Shop hidden",url,shop)}else undoBar(card,"Listing hidden and saved",url);menu.remove()};menu.append(b)});wrap.append(menu)
  };wrap.append(trigger);S.mountControls(card,wrap,url)
 }
 let ready=false;globalThis.FeedShieldProtectionSnapshot=()=>({ready,enabled:settings.protectionEnabled,siteEnabled:settings['etsyEnabled']});
 function cleanup(){document.querySelectorAll('[data-feedshield-item-site="Etsy"]').forEach(S.restore)}
 function run(reevaluate=false){if(!settings.protectionEnabled||!settings.etsyEnabled){cleanup();return}if(reevaluate)cleanup();listingCards().forEach(add)}
 FeedShieldBrowser.legacy.storage.local.get(defaults,c=>{settings={...defaults,...c};run();ready=true;});FeedShieldBrowser.legacy.storage.onChanged.addListener((ch,a)=>{if(a==="local"){for(const[k,v]of Object.entries(ch))settings[k]=v.newValue;run(['protectionEnabled','etsyEnabled','showPlaceholder','hiddenItems','blockedEtsyShops','customTerms'].some(k=>Object.hasOwn(ch,k)))}});new MutationObserver(()=>{clearTimeout(window.__fse);window.__fse=setTimeout(()=>run(),180)}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['href']});setInterval(()=>run(),3000)
})();
