(()=>{
 const defaults={protectionEnabled:true,etsyEnabled:true,blockedEtsyShops:[],manualFlags:[],hiddenItems:[],customTerms:""};let settings={...defaults};
 const norm=s=>(s||"").toLowerCase().replace(/\s+/g," ").trim(),custom=()=>settings.customTerms.split(/\n|,/).map(norm).filter(Boolean);
 function listingCards(){const set=new Set();document.querySelectorAll('a[href*="/listing/"]').forEach(a=>{const c=a.closest('li,article,[data-listing-id],div.wt-grid__item-xs-6');if(c&&(c.innerText||"").trim().length>3)set.add(c)});return[...set]}
 function shopName(card){for(const s of ['[data-shop-name]','.v2-listing-card__shop','.wt-text-caption','a[href*="/shop/"]']){const e=card.querySelector(s),v=e?.getAttribute('data-shop-name')||e?.textContent?.trim();if(v&&v.length<100)return v}return"Unknown shop"}
 function listingUrl(card){return card.querySelector('a[href*="/listing/"]')?.href||""}
 function saveFlag(meta){return new Promise(r=>chrome.storage.local.get({manualFlags:[],hiddenItems:[]},o=>{const a=Array.isArray(o.manualFlags)?o.manualFlags:[],h=Array.isArray(o.hiddenItems)?o.hiddenItems:[];a.unshift(meta);if(meta.url&&!h.includes(meta.url))h.unshift(meta.url);chrome.storage.local.set({manualFlags:a.slice(0,200),hiddenItems:h.slice(0,500)},r)}))}
 function blockShop(name){return new Promise(r=>{if(!name||name==="Unknown shop"){r();return}chrome.storage.local.get({blockedEtsyShops:[]},o=>{const a=o.blockedEtsyShops||[];if(!a.map(norm).includes(norm(name)))a.push(name);chrome.storage.local.set({blockedEtsyShops:a},r)})})}
 function undoBar(card,msg,url,shop){card.classList.add("feedshield-hidden");const old=document.querySelector(".feedshield-undo");if(old)old.remove();const bar=document.createElement("div");bar.className="feedshield-undo";bar.textContent=msg+" ";const b=document.createElement("button");b.textContent="Undo";b.onclick=()=>chrome.storage.local.get({hiddenItems:[],blockedEtsyShops:[]},o=>{const update={hiddenItems:(o.hiddenItems||[]).filter(x=>x!==url)};if(shop)update.blockedEtsyShops=(o.blockedEtsyShops||[]).filter(x=>norm(x)!==norm(shop));chrome.storage.local.set(update,()=>{Object.assign(settings,update);card.classList.remove("feedshield-hidden");bar.remove()})});bar.append(b);document.documentElement.append(bar);setTimeout(()=>bar.remove(),7000)}
 function add(card){
  if(card.dataset.feedshieldEtsy==="1")return;const url=listingUrl(card),shop=shopName(card),text=norm(card.innerText);
  if((settings.hiddenItems||[]).includes(url)||(settings.blockedEtsyShops||[]).map(norm).includes(norm(shop))||custom().some(x=>text.includes(x))){card.classList.add("feedshield-hidden");return}
  card.dataset.feedshieldEtsy="1";card.classList.add("feedshield-flag-host");const wrap=document.createElement("div");wrap.className="feedshield-etsy-controls";const trigger=document.createElement("button");trigger.textContent="Tell FeedShield";
  trigger.onclick=e=>{e.preventDefault();e.stopPropagation();const old=wrap.querySelector(".feedshield-etsy-menu");if(old){old.remove();return}const menu=document.createElement("div");menu.className="feedshield-etsy-menu";
   ["Suspected AI-generated artwork","AI-generated product mockup","Misleading handmade claim","Copied or mass-produced artwork","Product image may not match item","Suspicious digital download","Disturbing or sexualized image","Hide this shop","Something else"].forEach(reason=>{const b=document.createElement("button");b.textContent=reason;if(reason==="Hide this shop")b.className="danger";b.onclick=async ev=>{ev.preventDefault();ev.stopPropagation();const meta={site:"Etsy",reason,shop,url,title:(card.innerText||"").trim().slice(0,240),flaggedAt:new Date().toISOString()};await saveFlag(meta);if(reason==="Hide this shop"){await blockShop(shop);document.querySelectorAll('[data-feedshield-etsy="1"]').forEach(x=>{if(norm(shopName(x))===norm(shop))x.classList.add("feedshield-hidden")});undoBar(card,"Shop hidden",url,shop)}else undoBar(card,"Listing hidden and saved",url);menu.remove()};menu.append(b)});wrap.append(menu)
  };wrap.append(trigger);card.append(wrap)
 }
 function cleanup(){document.querySelectorAll(".feedshield-etsy-controls").forEach(x=>x.remove());document.querySelectorAll("[data-feedshield-etsy]").forEach(x=>{delete x.dataset.feedshieldEtsy;x.classList.remove("feedshield-flag-host")})}
 function run(){if(!settings.protectionEnabled||!settings.etsyEnabled){cleanup();return}listingCards().forEach(add)}
 chrome.storage.local.get(defaults,c=>{settings=c;run()});chrome.storage.onChanged.addListener((ch,a)=>{if(a==="local"){for(const[k,v]of Object.entries(ch))settings[k]=v.newValue;run()}});new MutationObserver(()=>{clearTimeout(window.__fse);window.__fse=setTimeout(run,180)}).observe(document.documentElement,{childList:true,subtree:true});setInterval(run,3000)
})();
