(()=>{
 const $=id=>document.getElementById(id),api=FeedShieldBrowser;let current,site,revision=0;
 const failure=error=>$('status').textContent=error.message;
 async function refresh(){const token=++revision;$('protection-status').textContent='Checking current page…';try{const result=await FeedShieldCurrentSite.inspect(api,current);if(token!==revision)return;site=result.site;$('protection-status').textContent=result.text;$('siteEnabled').disabled=!site;$('siteEnabled').checked=!!site&&current[site+'Enabled'];$('site-label').textContent=site?'Protect '+result.host:'Current site unsupported';$('diagnostics').textContent=JSON.stringify(result.diagnostics||{state:result.state},null,2);}catch(error){if(token===revision){$('protection-status').textContent='Current page status unavailable';failure(error);}}}
 FeedShieldSettings.subscribe(value=>{current=value;$('showPlaceholder').value=String(value.showPlaceholder);$('showPlaceholder').disabled=false;for(const id of ['protectionEnabled','blockAI','blockSponsored','chippyLiveEnabled']){$(id).checked=value[id];$(id).disabled=false;}$('saved-count').textContent=(value.manualFlags||[]).length+' saved items';$('chippy-status').textContent=value.chippyLiveEnabled?'Chippy enabled · appears on supported pages when placement is safe':'Chippy off · opt in to enable';refresh();});
 for(const id of ['protectionEnabled','blockAI','blockSponsored','chippyLiveEnabled','siteEnabled'])$(id).addEventListener('change',async()=>{const key=id==='siteEnabled'?site+'Enabled':id;$(id).disabled=true;try{await FeedShieldSettings.patch({[key]:$(id).checked});}catch(error){$(id).checked=current[key];failure(error);}finally{$(id).disabled=false;}});
 $('chippy-open').addEventListener('click',()=>api.runtime.sendMessage({type:'chippy.open'}).then(result=>{if(!result?.ok)throw Error(result?.error||'Could not open Chippy');window.close();}).catch(failure));
 $('showPlaceholder').onchange=()=>FeedShieldSettings.patch({showPlaceholder:$('showPlaceholder').value==='true'}).catch(failure);
 $('check-status').addEventListener('click',refresh);
 for(const action of ['later','quiet'])$(action).addEventListener('click',()=>FeedShieldSettings.request({type:'chippy.action',action}).then(()=>$('status').textContent=action==='later'?'Chippy snoozed for 10 minutes':'Chippy quiet today').catch(failure));
 for(const link of document.querySelectorAll('a[data-route]'))link.addEventListener('click',event=>{event.preventDefault();api.runtime.sendMessage({type:'app.open',route:link.dataset.route}).then(result=>{if(!result?.ok)throw Error(result?.error||'Could not open FeedShield');window.close();}).catch(failure);});
})();
