const siteOrigins={instagramEnabled:"https://www.instagram.com/*",facebookEnabled:"https://www.facebook.com/*",youtubeEnabled:"https://www.youtube.com/*",xEnabled:"https://x.com/*",redditEnabled:"https://www.reddit.com/*",pinterestEnabled:"https://www.pinterest.com/*",blueskyEnabled:"https://bsky.app/*",etsyEnabled:"https://www.etsy.com/*"};
const defaults={protectionEnabled:true,protectionLevel:"balanced",protectSexual:true,protectGraphic:true,protectAnimalHarm:true,protectHate:true,protectAI:true,protectMisleading:true,protectNews:true,protectPromotional:true,tiktokEnabled:true,instagramEnabled:true,facebookEnabled:true,youtubeEnabled:true,xEnabled:true,redditEnabled:true,pinterestEnabled:true,blueskyEnabled:true,etsyEnabled:true,blockSponsored:false,blockDrama:true,blockSexualized:true,blockAI:true,visualScan:true,autoHideVisual:true,visualThreshold:60,showPlaceholder:true,frameCount:4,sampleWindowMs:3000,customTerms:"DramaBox\nReelShort\nShortMax\nGoodShort\nFlexTV\nMoboReels",blockedAdvertisers:[],blockedCategories:[],allowedAdvertisers:[],blockedEtsyShops:[],blockedCreators:[],manualFlags:[],hiddenItems:[]};
const ids=["protectionEnabled","protectionLevel","protectSexual","protectGraphic","protectAnimalHarm","protectHate","protectAI","protectMisleading","protectNews","protectPromotional","tiktokEnabled",...Object.keys(siteOrigins),"blockSponsored","autoHideVisual","showPlaceholder","visualThreshold","frameCount","sampleWindowMs","customTerms"],$=id=>document.getElementById(id);
function status(t){$("status").textContent=t;setTimeout(()=>{if($("status").textContent===t)$("status").textContent=""},2200)}
function labels(){$("thresholdLabel").textContent=$("visualThreshold").value+"%";$("frameCountLabel").textContent=$("frameCount").value;$("sampleWindowLabel").textContent=(Number($("sampleWindowMs").value)/1000).toFixed(1)+"s"}
function counts(c){$("manualFlagsCount").textContent=(c.manualFlags||[]).length;$("blockedSourcesCount").textContent=(c.blockedEtsyShops||[]).length+(c.blockedAdvertisers||[]).length+(c.blockedCreators||[]).length}
function levelHelp(v){$("levelHelp").textContent={light:"Warns more often than it hides.",balanced:"Blurs likely matches while keeping an easy reveal option.",strong:"Hides more matches and may make more mistakes.",custom:"Uses the individual choices below."}[v]}
function applyLevel(v){const p={light:{visualThreshold:75,autoHideVisual:false},balanced:{visualThreshold:60,autoHideVisual:true},strong:{visualThreshold:45,autoHideVisual:true}}[v];if(p){$("visualThreshold").value=p.visualThreshold;$("autoHideVisual").checked=p.autoHideVisual}levelHelp(v);labels()}
function payload(){const p={};for(const id of ids){const e=$(id);p[id]=e.type==="checkbox"?e.checked:e.type==="range"?Number(e.value):e.value}p.blockDrama=p.protectPromotional;p.blockSexualized=p.protectSexual;p.blockAI=p.protectAI;p.visualScan=true;return p}
function persist(){chrome.storage.local.set(payload(),()=>status("Settings saved"))}
chrome.storage.local.get(defaults,c=>{for(const id of ids){const e=$(id);if(e.type==="checkbox")e.checked=c[id];else e.value=c[id]}counts(c);labels();levelHelp(c.protectionLevel)});
for(const id of ids){const e=$(id);if(id==="protectionLevel")continue;e.addEventListener(e.type==="range"?"input":"change",()=>{if(["visualThreshold","frameCount","sampleWindowMs"].includes(id)){$("protectionLevel").value="custom";levelHelp("custom");labels()}persist()})}
$("protectionLevel").addEventListener("change",e=>{applyLevel(e.target.value);persist()});
$("enableVisual").onclick=async()=>{const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!/^https:\/\/www\.tiktok\.com\//.test(tab.url||"")){status("Open TikTok first");return}try{const r=await chrome.tabs.sendMessage(tab.id,{type:"FEEDSHIELD_ENABLE_VISUAL_CHECK"});$("modelStatus").textContent=r?.ok?"Optional TikTok image check is ready":"Image check could not start";status(r?.ok?"Image check started":"Reload TikTok and try again")}catch{status("Reload TikTok and try again")}};
$("copyFlags").onclick=()=>chrome.storage.local.get(defaults,async c=>{const data={exportedAt:new Date().toISOString(),manualFlags:c.manualFlags||[],hiddenItems:c.hiddenItems||[],blockedAdvertisers:c.blockedAdvertisers||[],allowedAdvertisers:c.allowedAdvertisers||[],blockedCreators:c.blockedCreators||[],blockedEtsyShops:c.blockedEtsyShops||[]};try{await navigator.clipboard.writeText(JSON.stringify(data,null,2));status("Beta activity copied")}catch{status("Could not copy activity")}});
$("clearLists").onclick=()=>chrome.storage.local.set({manualFlags:[],hiddenItems:[],blockedAdvertisers:[],blockedCategories:[],allowedAdvertisers:[],blockedCreators:[],blockedEtsyShops:[]},()=>{counts(defaults);status("Saved activity cleared")});chrome.storage.onChanged.addListener(()=>chrome.storage.local.get(defaults,counts));
